// Mocks generated by Mockito 5.1.0 from annotations
// in quickagro/test/providers/user_profile_provider_test.dart.
// Do not manually edit this file.

import 'dart:ui' as _i3;

import 'package:quickagro/providers/user_profile_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UserProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileProvider extends _i1.Mock
    implements _i2.UserProfileProvider {
  MockUserProfileProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  set name(String? _name) => super.noSuchMethod(Invocation.setter(#name, _name),
      returnValueForMissingStub: null);
  @override
  String get phone =>
      (super.noSuchMethod(Invocation.getter(#phone), returnValue: '')
          as String);
  @override
  set phone(String? _phone) =>
      super.noSuchMethod(Invocation.setter(#phone, _phone),
          returnValueForMissingStub: null);
  @override
  String get defaultAddress =>
      (super.noSuchMethod(Invocation.getter(#defaultAddress), returnValue: '')
          as String);
  @override
  set defaultAddress(String? _defaultAddress) =>
      super.noSuchMethod(Invocation.setter(#defaultAddress, _defaultAddress),
          returnValueForMissingStub: null);
  @override
  String get email =>
      (super.noSuchMethod(Invocation.getter(#email), returnValue: '')
          as String);
  @override
  set email(String? _email) =>
      super.noSuchMethod(Invocation.setter(#email, _email),
          returnValueForMissingStub: null);
  @override
  String get profilePic =>
      (super.noSuchMethod(Invocation.getter(#profilePic), returnValue: '')
          as String);
  @override
  set profilePic(String? _profilePic) =>
      super.noSuchMethod(Invocation.setter(#profilePic, _profilePic),
          returnValueForMissingStub: null);
  @override
  String get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: '')
          as String);
  @override
  set userId(String? _userId) =>
      super.noSuchMethod(Invocation.setter(#userId, _userId),
          returnValueForMissingStub: null);
  @override
  Map<dynamic, dynamic> get stats =>
      (super.noSuchMethod(Invocation.getter(#stats),
          returnValue: <dynamic, dynamic>{}) as Map<dynamic, dynamic>);
  @override
  set stats(Map<dynamic, dynamic>? _stats) =>
      super.noSuchMethod(Invocation.setter(#stats, _stats),
          returnValueForMissingStub: null);
  @override
  List<dynamic> get allAddress =>
      (super.noSuchMethod(Invocation.getter(#allAddress),
          returnValue: <dynamic>[]) as List<dynamic>);
  @override
  set allAddress(List<dynamic>? _allAddress) =>
      super.noSuchMethod(Invocation.setter(#allAddress, _allAddress),
          returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  dynamic addAddress(String? title, String? address) =>
      super.noSuchMethod(Invocation.method(#addAddress, [title, address]));
  @override
  dynamic removeAddress(String? addressId) =>
      super.noSuchMethod(Invocation.method(#removeAddress, [addressId]));
  @override
  dynamic updatePhoneNumber(String? newPhone) =>
      super.noSuchMethod(Invocation.method(#updatePhoneNumber, [newPhone]));
  @override
  dynamic changePassword(String? currentPassword, String? newPassword) =>
      super.noSuchMethod(
          Invocation.method(#changePassword, [currentPassword, newPassword]));
  @override
  dynamic changeProfilePic(String? profilePicUrl) =>
      super.noSuchMethod(Invocation.method(#changeProfilePic, [profilePicUrl]));
  @override
  void addListener(_i3.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i3.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
